<?php
defined('ABSPATH') || exit;

add_action('init', function () {
    register_post_type('wpap_notifications', [
        'labels' => [
            'name' => __('Notifications', 'arvand-panel'),
            'singular_name' => __('Notice', 'arvand-panel'),
            'menu_name' => __('Notifications', 'arvand-panel'),
            'name_admin_bar' => __('Notice', 'arvand-panel'),
            'add_new' => __('Add New', 'arvand-panel'),
            'add_new_item' => __('Add Notice New', 'arvand-panel'),
            'new_item' => __('New Notice', 'arvand-panel'),
            'edit_item' => __('Edit Notice', 'arvand-panel'),
            'view_item' => __('Display Notice', 'arvand-panel'),
            'all_items' => __('Notifications', 'arvand-panel'),
            'search_items' => __('Search Notifications', 'arvand-panel'),
            'parent_item_colon' => __('Parent Notifications:', 'arvand-panel'),
            'not_found' => __('Not found notice.', 'arvand-panel'),
            'not_found_in_trash' => __('Not found notice in trash.', 'arvand-panel'),
            'featured_image' => __('Notice image', 'arvand-panel'),
            'set_featured_image' => __('Adjust notice image', 'arvand-panel'),
            'remove_featured_image' => __('Delete notice image', 'arvand-panel'),
            'use_featured_image' => __('Use as notice image', 'arvand-panel'),
            'archives' => __('Notifications archives', 'recipe'),
            'insert_into_item' => __('Insert into Notice', 'arvand-panel'),
            'uploaded_to_this_item' => __('Upload into notice', 'arvand-panel'),
            'filter_items_list' => __('Filter Notifications list', 'arvand-panel'),
            'items_list_navigation' => __('Notifications list navigation', 'arvand-panel'),
            'items_list' => __('Notifications List', 'arvand-panel'),
        ],
        'description' => 'notifications post type.',
        'public' => false,
        'show_ui' => true,
        'show_in_menu' => false,
        'query_var' => true,
        'rewrite' => ['slug' => 'wpap-notifications'],
        'capability_type' => 'post',
        'has_archive' => true,
        'hierarchical' => false,
        'supports' => ['title', 'editor'],
        'show_in_rest' => false
    ]);

    register_post_type('wpap_ticket', [
        'labels' => [
            'name' => 'Tickets',
            'singular_name' => __('Ticket', 'arvand-panel'),
            'menu_name' => __('Tickets', 'arvand-panel'),
            'name_admin_bar' => 'Ticket',
            'add_new' => __('Add New'),
            'add_new_item' => 'Add New Ticket',
            'new_item' => 'New Ticket',
            'edit_item' => 'Edit Ticket',
            'view_item' => 'Display Ticket',
            'all_items' => 'Tickets',
            'search_items' => 'Search Tickets',
            'parent_item_colon' => 'Parent Tickets:',
            'not_found' => 'Not found ticket.',
            'not_found_in_trash' => 'Not found ticket in trash.',
            'featured_image' => 'Ticket Image',
            'set_featured_image' => 'Adjust ticket image',
            'remove_featured_image' => 'Delete ticket image',
            'use_featured_image' => 'Use as a ticket image',
            'archives' => 'Tickets Archive',
            'insert_into_item' => 'insert into ticket',
            'uploaded_to_this_item' => 'Upload in this ticket',
            'filter_items_list' => 'Filter Tickets List',
            'items_list_navigation' => 'Tickets List Navigation',
            'items_list' => 'Tickets list',
        ],
        'description' => 'ticket post type.',
        'public' => false,
        'show_ui' => false,
        'show_in_menu' => false,
        'query_var' => false,
        'rewrite' => ['slug' => 'wpap-ticket'],
        'capability_type' => 'post',
        'has_archive' => false,
        'hierarchical' => true,
        'supports' => [],
        'show_in_rest' => false
    ]);

    register_post_type('wpap_private_message', [
        'labels' => [
            'name' => __('پیام ها', 'arvand-panel'),
            'singular_name' => __('پیام شخصی', 'arvand-panel'),
            'menu_name' => __('پیام ها', 'arvand-panel'),
            'name_admin_bar' => __('پیام ها', 'arvand-panel'),
            'add_new' => __('ارسال پیام جدید', 'arvand-panel'),
            'add_new_item' => __('ارسال پیام جدید', 'arvand-panel'),
            'new_item' => __('پیام جدید', 'arvand-panel'),
            'edit_item' => __('ویرایش پیام', 'arvand-panel'),
            'view_item' => __('نمایش پیام', 'arvand-panel'),
            'all_items' => __('پیام ها', 'arvand-panel'),
            'search_items' => __('جستجوی پیام ها', 'arvand-panel'),
            'parent_item_colon' => __('پیام والد', 'arvand-panel'),
            'not_found' => __('پیامی یافت نشد.', 'arvand-panel'),
            'not_found_in_trash' => __('پیامی در زباله دان یافت نشد.', 'arvand-panel'),
            'archives' => __('بایگانی پیام ها', 'arvand-panel'),
            'insert_into_item' => __('درج در پیام', 'arvand-panel'),
            'uploaded_to_this_item' => __('آپلود در این پیام', 'arvand-panel'),
            'filter_items_list' => __('فیلتر لیست پیام ها', 'arvand-panel'),
            'items_list_navigation' => __('ناوبری لیتت پیام ها', 'arvand-panel'),
            'items_list' => __('لیست پیام ها', 'arvand-panel')
        ],
        'public' => false,
        'show_ui' => false,
        'show_in_menu' => false,
        'query_var' => false,
        'rewrite' => ['slug' => 'wpap-private-message'],
        'capability_type' => 'post',
        'has_archive' => false,
        'hierarchical' => true,
        'supports' => ['title', 'editor', 'author'],
        'show_in_rest' => false
    ]);
});