<?php
defined( 'ABSPATH' ) || exit;

return [
    [
        'name' => 'notifications',
        'icon' => 'ri-notification-3-line',
        'icon_color' => '#0062f5',
        'icon_bg' => '#d6e9ff',
        'title' => __('Notifications', 'arvand-panel'),
        'content' => __('محتوای ویژۀ افزونه', 'arvand-panel'),
        'link' => '',
        'box_type' => 'default',
        'content_type' => __('Default content', 'arvand-panel'),
        'display' => 'show',
    ],
    [
        'name' => 'comments',
        'icon' => 'ri-chat-3-line',
        'icon_color' => '#f6743e',
        'icon_bg' => '#fdddd0',
        'title' => __('Comments', 'arvand-panel'),
        'content' => __('محتوای ویژۀ افزونه', 'arvand-panel'),
        'link' => '',
        'box_type' => 'default',
        'content_type' => 'default',
        'display' => 'show',
    ],
    [
        'name' => 'private_msg',
        'icon' => 'ri-message-line',
        'icon_color' => '#4eceaa',
        'icon_bg' => '#d0fff2',
        'title' => __('Private Message', 'arvand-panel'),
        'content' => __('محتوای ویژۀ افزونه', 'arvand-panel'),
        'link' => '',
        'box_type' => 'default',
        'content_type' => 'default',
        'display' => 'show',
    ],
    [
        'name' => 'user_registration_date',
        'icon' => 'ri-calendar-check-line',
        'icon_color' => '#ff0020',
        'icon_bg' => '#ffdbe0',
        'title' => __('تاریخ ثبت نام', 'arvand-panel'),
        'content' => __('محتوای ویژۀ افزونه', 'arvand-panel'),
        'link' => '',
        'box_type' => 'default',
        'content_type' => 'default',
        'display' => 'show',
    ],
    [

        'name' => 'completed_orders',
        'icon' => 'ri-checkbox-line',
        'icon_color' => '#00a8a8',
        'icon_bg' => '#cbf5f5',
        'title' => __('سفارش های تکمیل شده', 'arvand-panel'),
        'content' => __('محتوای ویژۀ افزونه', 'arvand-panel'),
        'link' => '',
        'box_type' => 'default',
        'content_type' => 'default',
        'display' => 'show',
    ],
    [
        'name' => 'wallet_amount',
        'icon' => 'ri-wallet-3-line',
        'icon_color' => '#929500',
        'icon_bg' => '#f0f297',
        'title' => __('مبلغ کیف پول', 'arvand-panel'),
        'content' => __('محتوای ویژۀ افزونه', 'arvand-panel'),
        'link' => '',
        'box_type' => 'default',
        'content_type' => 'default',
        'display' => 'show',
    ],
    [
        'name' => 'total_spent',
        'icon' => 'ri-money-dollar-circle-line',
        'icon_color' => '#04a400',
        'icon_bg' => '#dbffda',
        'title' => __('مجموع مبلغ خرید', 'arvand-panel'),
        'content' => __('محتوای ویژۀ افزونه', 'arvand-panel'),
        'link' => '',
        'box_type' => 'default',
        'content_type' => 'default',
        'display' => 'show',
    ],
    [
        'name' => 'total_items_bought',
        'icon' => 'ri-box-1-line',
        'icon_color' => '#a500ff',
        'icon_bg' => '#f3ddff',
        'title' => __('محصولات خریداری شده', 'arvand-panel'),
        'content' => __('محتوای ویژۀ افزونه', 'arvand-panel'),
        'link' => '',
        'box_type' => 'default',
        'content_type' => 'default',
        'display' => 'show',
    ],
];